### ISSUE TITLE
jdk11 JAR shows up even with <classifier>jdk8</classifier>

### ISSUE THREAD

**Issue by pcurrivan** [PgBulkInsert/PgBulkInsert#103]
I'm using JDK8 and I have the classifier tags in my pom file.

I got this error:
`Exception in thread "main" java.lang.UnsupportedClassVersionError: de/bytefish/pgbulkinsert/mapping/AbstractMapping has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

In my target folder I found the two jdk8 jars (core and rowwriter) as well as a jdk11 core jar. Deleting the jdk11 jar (pgbulkinsert-core-7.0.1.jar) seems to make things work properly.

**Comment by bytefish** [comment]
Could you share the relevant parts of the pom.xml, so I can give it a try.

**Comment by bytefish** [comment]
If you are using IntelliJ I found a somewhat similar problem described here:

* https://github.com/arnaudroger/SimpleFlatMapper/issues/677

Could you have a look if this applies to the issue here, too?

**Comment by bytefish** [comment]
Oh well sbould have read the whole thread, the author built the project with different artifactId names. I will keep investigating.

**Comment by bytefish** [comment]
It's apparently the project described here:

* https://youtrack.jetbrains.com/issue/IDEA-203432

I will see how complicated it is to update the artifactId, because honestly... this bug in IntelliJ has been not fixed for some years... and I don't think this is obvious to most people.

In the meantime, maybe you can set the JDK in IntelliJ to the projects JDK.

**Comment by bytefish** [comment]
Does it help to add this to your pom.xml:

```xml
<properties>
  <maven.compiler.source>1.8</maven.compiler.source>
  <maven.compiler.target>1.8</maven.compiler.target>
</properties>
```
Also see:

* https://stackoverflow.com/questions/25888023/how-to-change-java-version-for-maven-in-intellij

**Comment by pcurrivan** [comment]
Thanks for the prompt response.  I can't share much of the pom, but I did run mvn dependency:tree and I see that the jdk8 rowwriter depends on the jdk11 jar:
```
[INFO]    +- de.bytefish.pgbulkinsert:pgbulkinsert-core:jar:jdk8:7.0.1:compile
[INFO]    +- de.bytefish.pgbulkinsert:pgbulkinsert-rowwriter:jar:jdk8:7.0.1:compile
[INFO]    |  \- de.bytefish.pgbulkinsert:pgbulkinsert-core:jar:7.0.1:compile
```

Maybe you need to add a classifier or something to the rowwriter pom dependencies?

My IDE's importer was already using 1.8.  The source and target properties did not help.

**Comment by bytefish** [comment]
@pcurrivan Thanks, I will create a small sample today and try to reproduce it. @jonfreedman Can you see a problem with the definition for the JDK8?

**Comment by jonfreedman** [comment]
I'm not sure maven allows us to refer to the current project classifier in order to express that as a dependency. For now you should be able to fix this by excluding the transitive dependency of pgbulkinsert-core from pgbulkinsert-rowwriter.
We'll take a look at improving the way we support Java 8 vs Java 11

**Comment by bytefish** [comment]
@pcurrivan You should now be able to use the library with JDK8 using the following Maven Dependency:

```xml
<dependency>
    <groupId>de.bytefish</groupId>
    <artifactId>pgbulkinsert</artifactId>
    <version>8.0.0</version>
</dependency>
```

Please let us know, if it fixes the issue. 👍

**Comment by pcurrivan** [comment]
That fixes it, thanks.
