### ISSUE TITLE
Upsert support

### ISSUE THREAD

**Issue by SwapnilKhante** [PgBulkInsert/PgBulkInsert#109]
Hi,

I am following your flink experiment project and trying to setup a similar setup. So far it looks good however, I did not see supprt for doing an upsert operation. Is this possible with PgBulkInsert library ?

Thanks,
Swapnil

**Comment by bytefish** [comment]
No, the COPY Protocol, which is implemented in PgBulkInsert, only supports INSERTs. For UPSERT you would have to use JDBC statements.
