### ISSUE TITLE
How to map composite types?

### ISSUE THREAD

**Issue by yazun** [PgBulkInsert/PgBulkInsert#117]
Would it be possible?
And arrays of composite types that could have embedded arrays etc.. 
Thanks

**Comment by bytefish** [comment]
I think it would be possible, given that Npgsql is able to do it:

* https://github.com/npgsql/npgsql/blob/main/src/Npgsql/Internal/TypeHandlers/CompositeHandlers/CompositeHandler.cs

Do you have an SQL Example and an idea what an API in our library could look like?
