### ISSUE TITLE
Quoting algorithm is incorrect

### ISSUE THREAD

**Issue by juriad** [PgBulkInsert/PgBulkInsert#118]
The name of a table/column can be any sequence of up to 63 bytes except containing byte 0. Reference: https://www.postgresql.org/docs/14/sql-syntax-lexical.html

If my table is called:
* ", then it should be quoted as """" (4) instead of "
* "", then it should be quoted as """""" (6) instead of ""
* "x", then it should be quoted as """x""" (3+3) instead of "x"
* x"y then it should be quoted as "x""y" (1+2+1) instead of "x"y"

That is:
* any checks whether the identifier starts or ends with quotes is incorrect
* all quotes need to be doubles no matter where they are

Note that the first and last example will fail; the middle two may copy data into the wrong tables (if such tables happen to exist).

**Comment by bytefish** [comment]
I think for now you could disable the quoting algorithm using the  ``usePostgresQuoting`` constructor parameter. Then the given table or schema name is passed to the writer without quoting applied.

Feel free to make a PR! I think the relevant code for quoting is in the ``PostgreSqlUtils`` class. 👍

**Comment by bytefish** [comment]
This is how Npgsql applies quoting:

* https://github.com/npgsql/npgsql/blob/43756d15044ce20ea13424d6732a3defa6ce76cc/src/Npgsql/NpgsqlCommandBuilder.cs#L286

Do you think this is sufficient or covers your own examples? I didn’t look 👀 into it too deep, but it might be a good start.
