### ISSUE TITLE
Add support for Instant, OffsetDateTime

### ISSUE THREAD

**Issue by juriad** [PgBulkInsert/PgBulkInsert#119]
We support ZonedDateTime but not Instant and OffsetDateTime.
LocalDateTime, LocalDate and LocalTime are also candidates to support.

Moreover, OffsetDateTime is the default type to be used in the driver: https://jdbc.postgresql.org/documentation/head/java8-date-time.html

I am already hacking the support locally, so I may make a PR soon.

**Comment by bytefish** [comment]
@juriad Great! Let me know, if you need help from my side. 👍
