### ISSUE TITLE
Add the ability to use connection pooling with threading

### ISSUE THREAD

**Issue by StanLebedev** [PgBulkInsert/PgBulkInsert#122]
We can create a thread pool with different database connection from a connection pool.

**Comment by bytefish** [comment]
Could you give a little more details?

**Comment by StanLebedev** [comment]
We may use connection pooling with threading. We get faster insertion of objects.

ExecutorService executorService = Executors.newFixedThreadPool(poolSize);
executorService.invokeAll(...)

But I'm not sure if this should be added to the library.

**Comment by bytefish** [comment]
Yes, what I didn’t know when writing the library some years ago was, that Postgres opens one COPY per connection, so you can indeed get higher throughput when parallelizing the inserts.

The TimescaleDB team back then had the following to say, when I ran benchmarks against their database:

> My read of the writeup is that you are inserting with a single client / single COPY 
> command? That's actually "single threaded" on the server side, so it's very hard to > maximize insert rate with that. In fact, the whole reason we wrote a parallel COPY  
> tool. This will probably have the biggest impact: https://github.com/timescale/timescaledb-parallel-copy

I would most probably return Batched Entities as a ``Stream`` and call ``parallel()`` on it, so Java does all the Threading for me. But it depends on your use case. 

If it should be in the library, I don’t know. Most people don’t know, that parallelizing the whole COPY statements can be beneficial for Postgres (at least I didn’t know). 

So at least an example and a section in the README would be useful. 🤔

**Comment by StanLebedev** [comment]
not required
