### ISSUE TITLE
how to use PgBulkInsert library

### ISSUE THREAD

**Issue by fmachi** [PgBulkInsert/PgBulkInsert#128]
Hello,
I am working in a project for which I need to import periodically about 15 million rows to a PostgreSQL database on the cloud (AWS Rds). The data are uploaded by system users on a gdrive folder (zipped csv file). Our idea is to download the archive to one of our microservice pod (running on kubernetes) and to stream on it in order to import the content on our database.
Is this a scenario on which I can use your library?
I also have some other questions:
- am I forced to create a new table for each copy operation or can I just insert rows into an existing one?
- should/could I split the operation in different batches (maybe one million of rows at time)?
- do you have any estimation/analysis about the throughput I could observe?
- do you know any working example of this library usage inside a springboot microservice?
Thanks a lot!

**Comment by bytefish** [comment]
My honest answer. I like my library and I am sure it is useful for very efficient inserts. But if I‘d need to do a Bulk Insert these days? I would just do something along the lines of: 

* https://www.bytefish.de/blog/bulk_updates_postgres.html

And wouldn’t use the library at all. 🤷‍♂️ 

And if I’d write the procedure in the article today, I wouldn’t even declare a Type and do the Npgsql mapping… I would just send a JSON object to the SP. Is it a little slower, than a binary copy? *Maybe*, but I doubt it’s a lot and barely noticeable for 15 Million Rows.

In the Stored Procedure you can easily insert or update the rows. PgBulkInsert can only insert the data and this is often problematic, if you want to handle constraint violations and such. And it’s much easier to reason about.

I would look for a streaming CSV parser, batch the entities to 80.000 items and send them to something similar to the SP. I would do this concurrently on multiple connections, so Postgres spins up some threads.

**Comment by bytefish** [comment]
Also Postgres can insert a CSV, if it is compatible with the COPY Command: https://blog.skyvia.com/complete-guide-on-how-to-import-and-export-csv-files-to-postgresql/. 

So you could get away with not even coding more, than executing a command. But in my experience you really need some kind of error handling with CSV data for reporting invalid data.

But if you can get away with it, directly importing is also a nice idea.
