### ISSUE TITLE
ERROR: insufficient data left in message (float)

### ISSUE THREAD

**Issue by dimarudik** [PgBulkInsert/PgBulkInsert#129]
Dears, please help

public class App {
    public static void main(String[] args) {
        String url = args[0];
        try (Connection connection = DriverManager.getConnection(url)) {
            PGConnection pgConnection = PostgreSqlUtils.getPGConnection(connection);
            String schemaName = "rda";
            String tableName = "row_writer_test";
            String[] columnNames = new String[] {
                    "value_int",
                    "value_text",
                    "value_null",
                    "value_bool",
                    "value_float"
            };
            SimpleRowWriter.Table table = new SimpleRowWriter.Table(schemaName, tableName, columnNames);
            try(SimpleRowWriter writer = new SimpleRowWriter(table, pgConnection)) {
                for(int rowIdx = 0; rowIdx < 30; rowIdx++) {
                    writer.startRow((row) -> {
                        row.setText("value_text", "Hi \n ff\tend");
                        row.setInteger("value_int", 1);
                        row.setText("value_null", null);
                        row.setBoolean("value_bool", true);
                        row.setFloat("value_float", 32F);
                    });
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

and

java -jar PgBulkInsert-1.0-SNAPSHOT.jar "jdbc:postgresql://10.0.0.1:5432/rda?user=rda&password=rda"

Exception in thread "main" de.bytefish.pgbulkinsert.exceptions.BinaryWriteFailedException: org.postgresql.util.PSQLException: ERROR: insufficient data left in message
  Where: COPY row_writer_test, line 1, column value_float
	at de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter.close(PgBinaryWriter.java:214)
	at de.bytefish.pgbulkinsert.row.SimpleRowWriter.close(SimpleRowWriter.java:140)
	at org.example.App.main(App.java:36)
Caused by: org.postgresql.util.PSQLException: ERROR: insufficient data left in message
  Where: COPY row_writer_test, line 1, column value_float
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1299)
	at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:1095)
	at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:49)
	at org.postgresql.copy.PGCopyOutputStream.endCopy(PGCopyOutputStream.java:183)
	at org.postgresql.copy.PGCopyOutputStream.close(PGCopyOutputStream.java:113)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:189)
	at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:189)
	at de.bytefish.pgbulkinsert.pgsql.PgBinaryWriter.close(PgBinaryWriter.java:210)

**Comment by bytefish** [comment]
What does the SQL `CREATE TABLE` Statement look like?

**Comment by dimarudik** [comment]
rda=# alter table rda.row_writer_test add column value_float float8;
ALTER TABLE

rda=# \d+ rda.row_writer_test
                                                 Table "rda.row_writer_test"
   Column    |          Type          | Collation | Nullable | Default | Storage  | Compression | Stats target | Description
-------------+------------------------+-----------+----------+---------+----------+-------------+--------------+-------------
 value_int   | integer                |           |          |         | plain    |             |              |
 value_text  | character varying(255) |           |          |         | extended |             |              |
 value_null  | character varying(10)  |           |          |         | extended |             |              |
 value_bool  | boolean                |           |          |         | plain    |             |              |
 value_float | double precision       |           |          |         | plain    |             |              |
Access method: heap

**Comment by dimarudik** [comment]
create table row_writer_test
(
    value_int   integer,
    value_text  varchar(255),
    value_null  varchar(10),
    value_bool  boolean,
    value_float double precision
);

alter table row_writer_test
    owner to rda;

**Comment by dimarudik** [comment]
rda=# alter table rda.row_writer_test drop column value_float;
ALTER TABLE
rda=# alter table rda.row_writer_test add column value_float real;
ALTER TABLE

Working! Could you please fix it for float?

**Comment by bytefish** [comment]
I don't see, what fix needs to be done. `setFloat` expects you to map to a `real` column, as both represent a single point precision type. If you want to map to `double precision` type you need to use the `setDouble` method. If your data model has a float, then you probably need to cast it to a double... but I don't see the reason for having your Java model as a `single precision` and map to a `double precision` type.
