### ISSUE TITLE
Bulk insertion via the PostgreSQL JDBC using the PgBulkInsert is experiencing extended durations

### ISSUE THREAD

**Issue by vishnuvardankp-github** [PgBulkInsert/PgBulkInsert#130]
I attempted to insert a large number of records (specifically 99726 records) into my PostgreSQL database initially. The execution of the query and code took a maximum of 15 to 20 seconds.
Initially, I used the following query and code snippet for insertion:

```
 String sql = "COPY public.evt FROM STDIN WITH DELIMITER '|'";
Connection conn = writeJdbcTemplate.getDataSource().getConnection();
PGConnection pgConnection = conn.unwrap(org.postgresql.PGConnection.class);
CopyManager copyManager = pgConnection.getCopyAPI();
long affectedRows = copyManager.copyIn(sql, new ByteArrayInputStream(generateSlotDataInserts(slotDatas).getBytes(StandardCharsets.UTF_8)));
```
The generateSlotDataInserts method processes a `List<SlotData>` by iterating through it, storing the data in a `StringBuilder(),` appending each field with a delimiter `|`, and returning the StringBuilder as a String.
Later on, after consulting the PostgreSQL documentation, I discovered that the `COPY` command with `BINARY` format is regarded as the most efficient method for bulk record insertion. This led me to explore the `bytefish bulk insertion library`, and I attempted the following code snippet:

```
List<SlotData> slotDatas = new ArrayList<>();
for (int i = 0; i < slotsJsonArr.length; i++) {
    JSONObject js = (JSONObject) slotsJsonArr.get(i);
    SlotData slotData = new SlotData();
    slotData.setId("uuid goes here");
    slotData.setEventId("uuid goes here");
    slotData.setLocationType("store");
    slotData.setLocationId("id goes here");
    slotData.setDate("date");
    slotData.setStartTime("start time");
    slotData.setEndTime("end time");
    slotData.setTimezone("UTC");
    slotData.setCurrentRegistration(0);
    slotData.setCreated(ZonedDateTime.now());
    slotData.setCreatedBy("name");
    slotData.setLastModified(ZonedDateTime.now());
    slotData.setLastModifiedBy("name");
    slotData.setPreference(js.optJSONObject("preference"));
    slotDatas.add(slotData);
}

```
```
Connection conn = writeJdbcTemplate.getDataSource().getConnection();
PGConnection pgConnection = conn.unwrap(org.postgresql.PGConnection.class);
PgBulkInsert<SlotData> bulkInsert = new PgBulkInsert<>(new SlotDataMapping());
bulkInsert.saveAll(pgConnection, slotDatas.stream());
```

```
@Getter
@Setter
public class SlotData {
    private UUID id;
    private UUID eventId;
    private String locationType;
    private String locationId;
    private String date;
    private String startTime;
    private String endTime;
    private String timeZone;
    private int currentRegistration;
    private ZonedDateTime created;
    private String createdBy;
    private ZonedDateTime lastModified;
    private String lastModifiedBy;
    private JSONObject preference;

    public String getSlotPreferenceAsString() {
        return preference != null ? preference.toString() : null;
    }
}

```
```
public class SlotDataMapping extends AbstractMapping<SlotData> {
    public SlotDataMapping() {
        super("public", "evt");
        mapUUID("id", SlotData::getId);
        mapUUID("evnt_id", SlotData::getEventId);
        mapVarchar("loc_type", SlotData::getLocationType);
        mapVarchar("loc_id", SlotData::getLocationId);
        mapText("date", SlotData::getDate);
        mapText("start_time", SlotData::getStartTime);
        mapText("end_time", SlotData::getEndTime);
        mapText("timezone", SlotData::getTimeZone);
        mapInteger("registration", SlotData::getCurrentRegistration);
        mapTimeStampTz("created", SlotData::getCreated);
        mapVarchar("created_by", SlotData::getCreatedBy);
        mapTimeStampTz("last_modified", SlotData::getLastModified);
        mapVarchar("last_modified_by", SlotData::getLastModifiedBy);
        mapJsonb("preference", SlotData::getSlotPreferenceAsString);
    }
}
```

```
// Database schema: public
// Table name: evt
// Column names:
// id uuid,
// evnt_id uuid,
// loc_type varchar,
// loc_id varchar,
// date varchar,
// start_time varchar,
// end_time varchar,
// timezone bpchar,
// registration integer,
// created timestamp with timezone,
// created_by varchar,
// last_modified timestamp with timezone,
// last_modified_by varchar,
// preference jsonb
```
**Maven dependency:**
```
<dependency>
    <groupId>de.bytefish</groupId>
    <artifactId>pgbulkinsert</artifactId>
    <version>8.1.2</version>
</dependency>
```
 This code illustrates the process of creating SlotData objects from a JSON array, preparing them for bulk insertion using the **PgBulkInsert library,** and mapping fields via SlotDataMapping

Please note: I've disabled triggers for the table into which I'm currently inserting data. Additionally, when the method is annotated with **@Transactional (from Spring)**, the execution continues endlessly without any errors. However, upon running the query `select * from pg_stat_activity where state = 'active'`, I've noticed that the COPY query gets locked when the `@Transactional` annotation is enabled. Consequently, I've commented out the `@Transactional` annotation and proceeded to execute the code.

**Queries:**

1. Why does the execution of bulk inserts take longer when using bytefish PgBulkInsert?
2. What causes the COPY query to become locked when the @Transactional annotation is enabled?
3. Is it feasible to execute the COPY query in smaller batches to prevent excessive memory consumption that might lead to Kubernetes POD restarts?

**Comment by bytefish** [comment]
To speed up COPY Operations one should run them in parallel. I have always sent something around 100,000 elements, but your mileage may vary, it may depend on your data. One should run integration tests.

I didn’t see excessive memory consumption, as the data is read from a stream, streamed to Postgres and gets Garbage collected by the JVM. Hard to know, what’s happening in a Kubernetes POD and how Spring Boot handles connections. 

As for the deadlock. It’s the first report I am getting for deadlocks, and there can be a multitude of reasons. I am not a Spring Boot expert, so I have no idea what the TransactionManager for the Transaction-annotation does, what Isolation level is being used and what other things may put exclusive locks on the table. A COPY usually creates its own transaction or attaches to an existing.

**Comment by vishnuvardankp-github** [comment]
@bytefish 
Is it possible to insert bulk data in batches using this library?

**Comment by bytefish** [comment]
There is a BulkProcessor in the library, that does it. But honestly I would just create batches from the stream, return a stream of batches and insert them. Here is how you could create batches in Java:

* https://stackoverflow.com/a/30072617/513875
