### ISSUE TITLE
Does pgbulkinsert support postgis types?

### ISSUE THREAD

**Issue by xwl742** [PgBulkInsert/PgBulkInsert#131]
hello！How to set up mapping between Java String and Postgis Geometry?

**Comment by bytefish** [comment]
Reading through my libraries code again, I would say it does not fully support them. I do support Geometric types, as shown in the README, but I am not sure they are PostGIS equivalents. Half a decade ago I had implemented a PostGIS handler here:

* https://github.com/bytefish/PostGisBulkInsert

You should be able to copy and paste the few lines into your project. The README shows how to use it. And it *should* still work, given the APIs didn't change a lot for the dependencies.

**Comment by bytefish** [comment]
I have added update PostGisBulkInsert to the latest dependencies, so it should work with PgBulkInsert.

**Comment by bytefish** [comment]
Here is the 

* https://github.com/bytefish/PostGisBulkInsert/blob/master/PostGisBulkInsert/src/test/de/bytefish/postgisbulkinsert/integration/PostgisExtensionStringTest.java

It shows how you would insert from a `String`, which is given as [WKT](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry). It uses [sf-wkt](https://github.com/ngageoint/simple-features-wkt-java) for reading the data, and PostGisBulkInsert uses [sf-wkb](https://github.com/ngageoint/simple-features-wkb-java) for writing the data.
