### ISSUE TITLE
The  BigInteger incorrect write

### ISSUE THREAD

**Issue by ilyshkafox** [PgBulkInsert/PgBulkInsert#135]
Hi,

I am trying to create a table with the following structure:
CREATE TABLE target (
  test NUMBER(38)
);
I then try to insert a value using the SimpleRow class:
BigInteger integer = new BigInteger("999999999999999999999999999999999999");
row.setNumeric(0, integer);
However, when I run this code, the value 1000000000000000000000000000000000000 is being written to the database.

**Comment by bytefish** [comment]
Thanks for reporting! I am currently very busy at work, so I cannot promise a timeline. I don’t know, if you are literate with C#? I also have a Project called PostgreSQLCopyHelper. Is it reproducible there, or does it write the correct values. 

Npgsql has been my “inspiration” after all. 🤣

**Comment by bytefish** [comment]
It has been released to Central Maven Repositories as `8.1.5`. Sorry for the delay!
