### ISSUE TITLE
Can you help to support DataType.Time for write to PostgreSQL?

### ISSUE THREAD

**Issue by tangyibo** [PgBulkInsert/PgBulkInsert#83]
Hello: @bytefish 
   Can you help to support DataType.Time for write to PostgreSQL? I found DataType.time in class de.bytefish.pgbulkinsert.pgsql.constants.DataType, but i cannot find method wirte LocalTime data type in class de.bytefish.pgbulkinsert.row.SimpleRow, and can you help for support it ?
  Thank you very much!

**Comment by bytefish** [comment]
Yes, I think you are right! It's missing in the ``SimpleRow``. I will add it and release a new version to GitHub. But this may take some time, I have so many other things on my desk right now. 😵

If you can make a Pull Request I would be happy to accept.

**Comment by tangyibo** [comment]
@bytefish thanks!

**Comment by bytefish** [comment]
@tangyibo I have added the ``SimpleRow#setTime`` method to the ``SimpleRow`` implementation. It should be available as ``6.0.1`` as soon as the Maven Repositories update their index. Let me know, if this fixes your problem. 👍

**Comment by tangyibo** [comment]
Thanks very much!
