### ISSUE TITLE
Dont see jdk8 packages on maven central?

### ISSUE THREAD

**Issue by jeffzoch** [PgBulkInsert/PgBulkInsert#88]
Looking at https://mvnrepository.com/artifact/de.bytefish i dont see any packages with -jdk8 in them and when i use the pom dependencies specified in the changelog for java8 it fails.

**Comment by bytefish** [comment]
@jeffzoch I will investigate and fix it.

@jonfreedman Do yoi have an idea, why the Maven Central repos don't serve the jdk-8 version?

**Comment by bytefish** [comment]
@jeffzoch I think I got it wrong how the artifacts are published... and only checked Java11. 😳 I am sorry. The following should work. 

Could you let me know, if it fixes the problem?

```xml
<dependency>
  <groupId>de.bytefish.pgbulkinsert</groupId>
  <artifactId>pgbulkinsert-core</artifactId>
  <version>6.0.1</version>
  <classifier>jdk8</classifier>
</dependency>
```

**Comment by jeffzoch** [comment]
All good! ```    implementation("de.bytefish.pgbulkinsert:pgbulkinsert-core:$pgbulkinserVersion:jdk8")
``` is how it looks in gradle.

**Comment by bytefish** [comment]
Cool! 😎

Do you think it would be useful to include a Gradle example to the README?
